version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_USER=pharmacy_user
      - DB_HOST=database
      - DB_NAME=pharmacy_db
      - DB_PASSWORD=password
      - DB_PORT=5432
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"

  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=pharmacy_db
      - POSTGRES_USER=pharmacy_user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"